GET http://localhost:4000/routines

###
GET http://localhost:4000/todos

###
POST http://localhost:4000/todos
content-type: application/json

{
    "title": "Testing",
    "description": "Testing restructure of the project"
}

###
PUT http://localhost:4000/todos/64ea396ec84ff760dcb32cf8
content-type: application/json

{
    "title": "Testing updated",
    "description": "Testing restructure of the project updated"
}

###
DELETE http://localhost:4000/todos/64ea386457742a32cac1a9fc

###
GET http://localhost:4000/topics

###
GET http://localhost:4000/topics/random/10

###
POST http://localhost:4000/topics
Content-Type: application/json

{
    "title": "Test",
    "url": "http://www.example.com"
}